## Numpy Practice (0.5 point)

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [7]:
#1
import numpy as np;
mat = np.zeros((10, 10), dtype=int)
mat[0] = mat[9] = 1
mat[:, 0] = mat[:, 9] = 1
print(mat)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


2. Create a 5*5 matrix with each row being 0 to 4

In [5]:
#2
print(np.tile(np.arange(5), (5, 1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [9]:
#3
print(np.tile(np.array([[0, 1], [1, 0]]), (4, 4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [14]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[arr & 1 == 1])

[1 3 5 7 9]


5. Normalize a 5x5 random matrix that follows the Gaussian distribution N(4,3).(Z-Score Normalization零均值归一化)

In [ ]:
#5
print(np.random.normal(4, 3, (5, 5)))

[[ 2.91651288  3.79348454  6.67056945  5.49822333  4.49481285]
 [ 7.21353291  2.84970984  2.55189468  5.83861752  5.11750553]
 [ 8.77705817  3.10300809  4.98539262  1.26402929  3.31481857]
 [ 1.3303951  -2.54993812  3.31722768  2.03239892  5.73955777]
 [ 1.96304054  5.14938912  4.49015624  7.68195204  4.9756646 ]]


6. Consider a random positive 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [ ]:
#6
mat = np.random.rand(10, 2)
r = np.linalg.norm(mat, axis=1)
theta = np.arctan2(mat[:, 1], mat[:, 0])
print(mat)
print(r)
print(theta)
print(np.c_[r, theta])

TypeError: random() takes at most 1 positional argument (2 given)

7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [21]:
#7
arr = np.array([1, 2, 3, 4, 5])
res = np.zeros(5 + 3 * 4, dtype=int)
res[::4] = arr
print(res)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 

hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2)

First guess a result, then print the result, and finally find why

In [18]:
#8
print(0 * np.nan);

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [22]:
#9
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Tsawke\AppData\Local\Temp\ipykernel_17520\2370070070.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Tsawke\AppData\Local\Temp\ipykernel_17520\2370070070.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Tsawke\AppData\Local\Temp\ipykernel_17520\2370070070.py:6: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))
